### ISSUE TITLE
Toggl entry duration always rounds down to the nearest minute

### ISSUE THREAD

**Issue by supremebeing7** [supremebeing7/time_log_robot#28]
```
# lib/time_log_robot/toggl/entry.rb
  def duration_in_seconds
    # Toggl sends times in milliseconds
    @duration_in_seconds ||= raw_entry['dur']/1000
  end
```

One approach: `(raw_entry['dur']/1000.to_f).round`

**Comment by Parmandil** [comment]
Should be fixed by https://github.com/supremebeing7/time_log_robot/pull/29.  Perhaps there is a nicer-looking way, but the problem isn't really in Toggl, it's in how Jira logs time, so I think the fix really belongs in Jira's logger, not Toggl's seconds calculation. If integrating Toggl with something that really did log in seconds we wouldn't want Toggl rounding to nearest minute.

**Comment by supremebeing7** [comment]
Makes sense! And my approach above wouldn't even solve the issue. Not sure what I was thinking, but all that one would do is round to the nearest second, rather than rounding down to the second. Theoretically, the robot should probably do that too, but that's not really a big issue at the moment.
